package vn.napas.webrp.database.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.RowMapper;

import lombok.Data;
@Data
public class ShclogSettIbftAdjustDto {
	private Long id;
	private BigDecimal msgtype;
	private String pan;
	private String pcode;
	private BigDecimal amount;
	private BigDecimal acqCurrencyCode;
	private BigDecimal feeIss;
	private BigDecimal feeAcq;
	private BigDecimal trace;
	private BigDecimal localTime;
	private LocalDateTime localDate;
	private LocalDateTime settlementDate;
	private String acquirer;
	private String issuer;
	private BigDecimal respcode;
	private BigDecimal merchantType;
	private BigDecimal chCurrencyCode;
	private String termid;
	private String acctnum;
	private BigDecimal issCurrencyCode;
	private LocalDateTime trandate;
	private BigDecimal trantime;
	private String cardproduct;
	private BigDecimal revcode;
	private BigDecimal origtrace;
	private String acceptorname;
	private String termloc;
	private LocalDateTime tgGuiqt;
	private LocalDateTime tgXlnv;
	private LocalDateTime tgGuinv;
	private LocalDateTime tgGuiqtp;
	private LocalDateTime editDate;
	private String editUser;
	private String smlVerify;
	private String origiss;
	private BigDecimal origrespcode;
	private BigDecimal isrev;
	private BigDecimal preamount;
	private LocalDateTime capDate;
	private String authnum;
	private BigDecimal thu;
	private BigDecimal thuRefun;
	private BigDecimal tt1;
	private BigDecimal tt2;
	private BigDecimal tt3;
	private BigDecimal tt4;
	private BigDecimal pPcode;
	private BigDecimal settlementAmount;
	private BigDecimal cardholderAmount;
	private BigDecimal settlementConvRate;
	private BigDecimal cardholderConvRate;
	private BigDecimal bbBin;
	private BigDecimal forwardInst;
	private BigDecimal transferee;
	private String refnum;
	private BigDecimal settCurrencyCode;
	private BigDecimal preCardholderAmount;
	private BigDecimal merchantTypeOrig;
	private String onlySml;
	private String feeNote;
	private BigDecimal acquirerFe;
	private BigDecimal acquirerRp;
	private BigDecimal issuerFe;
	private BigDecimal issuerRp;
	private BigDecimal rcIss72;
	private BigDecimal rcAcq72;
	private BigDecimal pcode2;
	private String fromSys;
	private String tranCase;
	private BigDecimal bbBinOrig;
	private String src;
	private String des;
	private BigDecimal pcodeOrig;
	private String rcIss;
	private String rcBen;
	private LocalDateTime napasDate;
	private LocalDateTime napasEditDate;
	private String addResponse;
	private String mvv;
	private BigDecimal stt;
	private BigDecimal feeIrfIss;
	private BigDecimal feeSvfIss;
	private BigDecimal feeIrfAcq;
	private BigDecimal feeSvfAcq;
	private BigDecimal feeIrfPayAt;
	private BigDecimal feeSvfPayAt;
	private BigDecimal feeIrfRecAt;
	private BigDecimal feeSvfRecAt;
	private BigDecimal feeIrfBen;
	private BigDecimal feeSvfBen;
	private BigDecimal posConditionCode;
	private BigDecimal posEntryCode;
	private String tcc;
	private String feeKey;
	private BigDecimal acqCountry;
	private String termid1;
	private String token;
	private BigDecimal rc;
	private BigDecimal settlementCode;
	private BigDecimal settlementRate;
	private BigDecimal issConvRate;
	private BigDecimal f49;
	private BigDecimal f5;
	private BigDecimal f4;
	private BigDecimal f6;
	private BigDecimal svfissnp;
	private BigDecimal irfissacq;
	private BigDecimal irfissbnb;
	private BigDecimal svfacqnp;
	private BigDecimal irfacqiss;
	private BigDecimal irfacqbnb;
	private BigDecimal svfbnbnp;
	private BigDecimal irfbnbiss;
	private BigDecimal irfbnbacq;
	private BigDecimal reFee;
	private String issSend;
	private String acqSend;
	private String bnbSend;
	private String txnSrc;
	private String txnDest;
	private BigDecimal preamountUsd;
	private String contentFund;
	private BigDecimal dataId;
	private String addInfo;
	private BigDecimal preamountAcq;
	private String f60Upi;
	private String f100Upi;
	private BigDecimal isPartRev;
	private String transitCsrr;
	private String msgtypeDetail;
	
	
}
