INSERT INTO ISOMESSAGE_TMP_TURN(SEQ_NO, MTI, CARD_NO, PROC_CODE, ORIGINAL_DATE, TRACE_NO, REF_NO, ACQ_ID, ISS_ID,
    APPROVAL_CODE, RESPONSE_CODE,TERM_ID, ORIGINAL_DATA, REVERSED, TNX_STAMP, PACKAGER, AMOUNT,
    ACCOUNT_NO, LOCAL_TIME, LOCAL_DATE, SETTLE_DATE,MCC, CURRENCY_CODE, DEST_ACCOUNT,
    RECONCILE_TIME, TRANX_DATE, ADD_INFO, SERVICE_CODE, VAS_INFO, BEN_ID,ORIGRESPCODE, IBFT_INFO,
        --TCKTM
        ACQ_COUNTRY, POS_ENTRY_CODE, POS_CONDITION_CODE, ADDRESPONSE, MVV, F4,
        F5, F6, F49, SETTLEMENT_CODE, SETTLEMENT_RATE,
        ISS_CONV_RATE,TCC,CARD_ACCEPT_NAME_LOCATION,CARD_ACCEPT_ID_CODE,OF_YEAR)
Select SEQ_NO, MTI, Decode(Trim(CARD_NO),null,'',Trim(CARD_NO)), PROC_CODE, ORIGINAL_DATE, TRACE_NO, REF_NO, ACQ_ID, ISS_ID,
    APPROVAL_CODE, RESPONSE_CODE,TERM_ID, ORIGINAL_DATA, REVERSED, TNX_STAMP, PACKAGER, AMOUNT_SETTLEMENT,
    ACCOUNT_NO, LOCAL_TIME, LOCAL_DATE, SETTLE_DATE,MCC, Decode(TRIM(CURRENCY_CODE),'USD',840,'VDD',704,'VND',704,CURRENCY_CODE), DEST_ACCOUNT,
    RECONCILE_TIME, TRANX_DATE, ADD_INFO, SERVICE_CODE, VAS_INFO, BEN_ID,RESPONSE_CODE,
    Case When Length(Trim(IBFT_INFO)) > 210 Then SUBSTR (Trim(IBFT_INFO), 0, 210)
        Else Trim(IBFT_INFO)
    End,
        ACQ_INST_COUNTRY_CODE, POS_ENTRY_MODE, POS_CONDITION_CODE, TRANX_REF, SERVICE_CODE, AMOUNT,
        AMOUNT_SETTLEMENT, AMOUNT_CARDHOLDER, Decode(TRIM(CURRENCY_CODE),'USD',840,'VDD',704,'VND',704,CURRENCY_CODE),
        Decode(CURRENCY_CODE_SETTLEMENT,'   ',704,'.  ',704,CURRENCY_CODE_SETTLEMENT), CONVERSION_RATE_SETTLEMENT,CONVERSION_RATE_CARDHOLDER,
        USER_DEFINE,CARD_ACCEPT_NAME_LOCATION,CARD_ACCEPT_ID_CODE,PAYMENT_CODE
From IPSIBT20.ISOMESSAGE@NEW_IPSIBT
Where SETTLE_DATE = To_Char(To_Date('04/09/2025','dd/mm/yyyy'),'mmdd')
And Substr(proc_code,1,2) in ('42','91')
And MTI in('0200','0210')
And ACQ_ID <> '605609'
and (ISS_ID is null 
  or ISS_ID in (980472,980471,980474,980475))--ninhnt sua cho IBFT 2.0