MERGE INTO
    (SELECT ISSUER_RP,ISSUER,FEE_PACKAGE_TYPE,INS_TYPE_FEE
        FROM SHCLOG_SETT_IBFT
     ) A
    USING 
        (SELECT SHCLOG_ID,FEE_PACKAGE_TYPE,INS_TYPE_FEE
            FROM RP_INSTITUTION
         ) B
    ON  
        (
            Decode(A.ISSUER_RP,980471,A.ISSUER,980478,A.ISSUER,A.ISSUER_RP)=B.SHCLOG_ID
        )                   
    WHEN MATCHED THEN                    
        UPDATE SET A.FEE_PACKAGE_TYPE = B.FEE_PACKAGE_TYPE,A.INS_TYPE_FEE=B.INS_TYPE_FEE