Insert Into TBL_PAYMENT(ID,CARD_NO,TRACE_NO,LOCAL_DATE,LOCAL_TIME,ACQ_ID,TERM_ID,BEN_ID,ACCOUNT_NO,DEST_ACCOUNT,
RESPCODE_NAPAS,RESPCODE_TCNL,TNX_STAMP,SETTLE_DATE,MTI,CREATION_DATETIME,MODIF_DATETIME,ACH_TXID,ACH_CONFIRM,
ACH_TRANS_STATUS,SYSTEM_DIRECTION,MESSAGE_INPUT_ID)
Select distinct ID,CARD_NO,TRACE_NO,LOCAL_DATE,LOCAL_TIME,ACQ_ID,TERM_ID,BEN_ID,ACCOUNT_NO,DEST_ACCOUNT,
RESPCODE_NAPAS,RESPCODE_TCNL,TNX_STAMP,SETTLE_DATE,MTI,CREATION_DATETIME,MODIF_DATETIME,ACH_TXID,ACH_CONFIRM,
ACH_TRANS_STATUS,SYSTEM_DIRECTION,MESSAGE_INPUT_ID
From IPSINQUIRY.TBL_PAYMENT@LINKACHTEST
Where SETTLE_DATE = To_Date('07/09/2025','dd/mm/yyyy')
And system_direction in ('ACH_IBFT', 'IBFT_IBFT', 'IBFT_ACH')
--and IBFT10 = 'Y'
And MTI in ('0200','0210')
And RESPCODE_TCNL is not null
