MERGE INTO (
            SELECT MSGTYPE,TRIM(PAN) AS PAN,LPAD(ORIGTRACE,6,'0') AS ORIGTRACE,TO_CHAR(LOCAL_DATE,'MMDD') AS LOCAL_DATE,
                LPAD(LOCAL_TIME,6,'0') AS LOCAL_TIME,ORIGRESPCODE,TERMID,DEST_ACCOUNT,RESPCODE,ACQUIRER,EDIT_USER
            FROM SHCLOG_SETT_IBFT
            WHERE MSGTYPE = '0210'
            AND ORIGRESPCODE in (68,97)
            AND MVV ='IF_DEP'
            AND DECODE(BB_BIN,NULL,0,BB_BIN) not in (971100, 971111, 971122)
            ) A
USING (SELECT /*+ index (TBL_PAYMENT TBL_PAYMENT_IDX) */ MTI,CARD_NO,TRACE_NO,LOCAL_DATE,LOCAL_TIME,ACQ_ID,TERM_ID,RESPCODE_TCNL,DEST_ACCOUNT,RESPCODE_NAPAS  
        FROM TBL_PAYMENT
        WHERE IS_NUMBER(RESPCODE_TCNL) > 0
        ) B
ON (A.PAN= B.CARD_NO
    AND A.ORIGTRACE = B.TRACE_NO
    AND A.LOCAL_DATE= B.LOCAL_DATE
    AND A.LOCAL_TIME=B.LOCAL_TIME
    AND A.TERMID= B.TERM_ID  
    AND A.DEST_ACCOUNT=B.DEST_ACCOUNT 
    AND A.ACQUIRER =B.ACQ_ID                
)
WHEN MATCHED THEN
    UPDATE SET A.RESPCODE =
        CASE 
            WHEN A.ORIGRESPCODE= 68 AND B.RESPCODE_NAPAS = 68 AND B.RESPCODE_TCNL ='00' THEN 0
            WHEN A.ORIGRESPCODE= 68 AND B.RESPCODE_NAPAS = 68 AND B.RESPCODE_TCNL <> '00' THEN TO_NUMBER(B.RESPCODE_TCNL)
            WHEN A.ORIGRESPCODE= 97 AND B.RESPCODE_TCNL = '00' THEN 0
            WHEN A.ORIGRESPCODE= 97 AND B.RESPCODE_TCNL <> '00' THEN TO_NUMBER(B.RESPCODE_TCNL)
            ELSE A.RESPCODE
        END,
        A.EDIT_USER ='Cap nhat GD truy van tu TCNL'