
CREATE TABLE RPT.ISOMESSAGE_TMP_TURN
(
  SEQ_NO                      NUMBER(12),
  MTI                         VARCHAR2(12 BYTE),
  CARD_NO                     VARCHAR2(57 BYTE),
  PROC_CODE                   VARCHAR2(18 BYTE),
  ORIGINAL_DATE               VARCHAR2(30 BYTE),
  TRACE_NO                    VARCHAR2(18 BYTE),
  REF_NO                      VARCHAR2(36 BYTE),
  ACQ_ID                      VARCHAR2(33 BYTE),
  ISS_ID                      VARCHAR2(33 BYTE),
  APPROVAL_CODE               VARCHAR2(18 BYTE),
  RESPONSE_CODE               VARCHAR2(9 BYTE),
  TERM_ID                     VARCHAR2(24 BYTE),
  ORIGINAL_DATA               VARCHAR2(4000 BYTE),
  REVERSED                    VARCHAR2(3 BYTE),
  TNX_STAMP                   DATE,
  PACKAGER                    VARCHAR2(300 BYTE),
  AMOUNT                      NUMBER(15),
  ACCOUNT_NO                  VARCHAR2(69 BYTE),
  LOCAL_TIME                  VARCHAR2(18 BYTE),
  LOCAL_DATE                  VARCHAR2(12 BYTE),
  SETTLE_DATE                 VARCHAR2(12 BYTE),
  MCC                         VARCHAR2(12 BYTE),
  CURRENCY_CODE               VARCHAR2(9 BYTE),
  DEST_ACCOUNT                VARCHAR2(69 BYTE),
  RECONCILE_TIME              DATE,
  TRANX_DATE                  DATE,
  ADD_INFO                    VARCHAR2(765 BYTE),
  SERVICE_CODE                VARCHAR2(90 BYTE),
  VAS_INFO                    VARCHAR2(600 BYTE),
  BEN_ID                      VARCHAR2(33 BYTE),
  OF_YEAR                     VARCHAR2(4 BYTE),
  ISREV                       INTEGER,
  ORIGRESPCODE                VARCHAR2(9 BYTE),
  IBFT_INFO                   VARCHAR2(300 BYTE),
  AMOUNT_SETTLEMENT           NUMBER(26,8),
  AMOUNT_CARDHOLDER           NUMBER(26,8),
  CURRENCY_CODE_SETTLEMENT    VARCHAR2(9 BYTE),
  CURRENCY_CODE_CARDHOLDER    VARCHAR2(9 BYTE),
  CONVERSION_RATE_SETTLEMENT  VARCHAR2(8 BYTE),
  CONVERSION_RATE_CARDHOLDER  VARCHAR2(8 BYTE),
  USER_DEFINE                 VARCHAR2(60 BYTE),
  TRANX_REF                   VARCHAR2(16 BYTE),
  ACQ_COUNTRY                 NUMBER(28,2),
  POS_ENTRY_CODE              NUMBER(28,2),
  POS_CONDITION_CODE          NUMBER(28,2),
  ADDRESPONSE                 NVARCHAR2(25),
  MVV                         NVARCHAR2(20),
  F4                          NUMBER(26,8),
  F5                          NUMBER(26,8),
  F6                          NUMBER(26,8),
  F49                         INTEGER,
  SETTLEMENT_CODE             INTEGER,
  SETTLEMENT_RATE             NUMBER(26,8),
  ISS_CONV_RATE               NUMBER(26,8),
  TCC                         VARCHAR2(64 BYTE),
  RC_210                      VARCHAR2(3 BYTE),
  CARD_ACCEPT_NAME_LOCATION   VARCHAR2(40 BYTE),
  CARD_ACCEPT_ID_CODE         VARCHAR2(15 BYTE)
)

